# add the following to _config.yml file
title: Neha Tandon

logo: me.jpg # Use a relative path to logo image 

description: ML in signal processing # Fix hyphenation 

show_downloads: true # Fix spelling

email: nehat005@gmail.com # Allow visitors to contact you

remote_theme: hydecorp/hydejack
