# add the following to _config.yml file
title: Neha Tandon

logo: 1.png # Use a relative path to logo image 

description: Data science and AI in agriculture - where bytes and botany blend for a better world. # Fix hyphenation 

show_downloads: true # Fix spelling

email: nehat005@gmail.com # Allow visitors to contact you

remote_theme: hydecorp/hydejack
